syntax on

"source! ~/.vim/vim_dvorak
map <F8> :!make
map ge ia:-V:! tr 'aeiouAEIOUáéíóúÁÉÍÓÚnNñÑ' 'áéíóúÁÉÍÓÚaeiouAEIOUñÑnN'i$ni

set numberwidth=3
set number
highlight LineNr term=NONE cterm=NONE ctermfg=Blue  ctermbg=NONE gui=NONE guifg=DarkGrey guibg=NONE
highlight QuickFixLine ctermbg=DarkGrey

"Disable obnoxious search features
set nohlsearch
set noincsearch

"filetype plugin indent on
set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
"set smartindent
set expandtab
set hidden
set ignorecase
set smartcase
set mouse=a
set guicursor=

set listchars=tab:>-,trail:·,eol:$
let mapleader = ","
nnoremap <silent> <leader>n :NERDTreeToggle<CR>
nnoremap <silent> <leader>s :set list!<CR>
nnoremap <silent> <leader>c :cfile<CR>
        
filetype plugin on
au BufNewFile,BufRead *.rkt set filetype=racket
au BufNewFile,BufRead *.scrbl set filetype=racket
au BufNewFile,BufRead *.rktl set filetype=racket
au BufNewFile,BufRead *.rktd set filetype=racket
au BufNewFile,BufRead *.yaspl set filetype=racket
au BufNewFile,BufRead *.cyaspl set filetype=racket
au BufNewFile,BufRead *.bzl set filetype=python
au Filetype racket set lisp
au Filetype racket set textwidth=102
au Filetype racket setlocal formatprg=
au Filetype scheme set textwidth=102
au Filetype python set shiftwidth=2
au Filetype python set smartindent


set nowritebackup
set directory=~/tmp/vimswp

"shift tab works
cmap <Esc>[Z <s-tab>
set nocompatible
set backspace=indent,eol,start
set whichwrap=h,l,~,[,],s,b
set laststatus=2


inoremap <c-h> <c-k>
inoremap <c-g> <c-k>*

dig BN 8469 "ℕ
dig BZ 8484 "ℤ
dig BC 8450 "ℂ
dig BQ 8474 "ℚ
dig BR 8477 "ℝ
dig du 8846 "⊎
dig c+ 8853 "⊕
dig c* 8855 "⊗
dig c= 8860 "⊜
dig c- 8854 "⊖
dig cc 169 "©
dig [[ 10214 "⟦
dig ]] 10215 "⟧
dig =v 8659 "⇓
dig hS 688 "ʰ
dig Sh 688 "ʰ
dig Si 8305 "ⁱ
dig Se 7497 "ᵉ
dig nS 8319 "ⁿ
dig Sn 8319 "ⁿ
dig TS 7488 "ᵀ
dig ST 7488 "ᵀ

dig Sr 691 "ʳ
dig Sl 737 "ˡ
dig SD 7472 "ᴰ
dig S2 178 "²
dig S3 179 "³
dig s4 8324 "₄
dig sc 8852 "⊔
dig sn 8345 "ⁿ
dig ns 8345 "ⁿ
dig ns 8345 "ⁿ
dig is 7522 "ᵢ
dig si 7522 "ᵢ

dig l> 10230 "⟶
dig .> 8674 "⇢
dig ll 8467 "ℓ
dig ii 119998 "𝒾
dig </ 10216 "⟨
dig /> 10217 "⟩
dig @< 8826 "≺
dig @> 8827 "≻
dig <@ 8828 "≼
dig >@ 8829 "≽
dig \|\| 8739 "∣
dig !{ 8713 "∉
dig s* 8902 "⋆
dig *s 963 "σ
dig I& 8523 "⅋
dig c> 8618 "↪
dig 2> 8608 "↠
dig tt 8868 "⊤
dig ff 8869 "⊥
dig \|- 8866 "⊢
dig pd 10178 "⟂
dig U) 8899 "⋃
dig U( 8898 "⋂
dig !( 2209 "





lnoremap <c-c> <ESC>
inoremap <c-c> <ESC>

"Setup racket
if has('mzscheme')
  mzscheme (current-library-collection-paths (find-library-collection-paths))
endif
